//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dental_sys
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenhNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BenhNhan()
        {
            this.BuoiDieuTris = new HashSet<BuoiDieuTri>();
            this.CuocHens = new HashSet<CuocHen>();
            this.BenhNens = new HashSet<BenhNen>();
        }
    
        public int id { get; set; }
        public string TenBenhNhan { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public string NgheNghiep { get; set; }
        public string LienHe { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public byte[] AnhChup { get; set; }
        public Nullable<int> NguoiTiepNhan { get; set; }
        public Nullable<System.DateTime> NgayTiepNhan { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuoiDieuTri> BuoiDieuTris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuocHen> CuocHens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BenhNen> BenhNens { get; set; }
    }
}
