//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dental_sys
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuoiDieuTri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BuoiDieuTri()
        {
            this.DonThuocs = new HashSet<DonThuoc>();
            this.HinhAnhDieuTris = new HashSet<HinhAnhDieuTri>();
            this.DichVus = new HashSet<DichVu>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> NgayKham { get; set; }
        public string ChuanDoan { get; set; }
        public Nullable<int> ChiPhi { get; set; }
        public Nullable<int> BacSi { get; set; }
        public Nullable<int> BenhNhan { get; set; }
        public string GhiChu { get; set; }
    
        public virtual BenhNhan BenhNhan1 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonThuoc> DonThuocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnhDieuTri> HinhAnhDieuTris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DichVu> DichVus { get; set; }
    }
}
