//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dental_sys
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonThuoc
    {
        public int id { get; set; }
        public string TenThuoc { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string Donvi { get; set; }
        public Nullable<int> Donthuoc_id { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string HuongDan { get; set; }
    
        public virtual DonThuoc DonThuoc { get; set; }
    }
}
