//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dental_sys
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuocHen
    {
        public int id { get; set; }
        public Nullable<int> BacSi { get; set; }
        public Nullable<int> BenhNhan { get; set; }
        public Nullable<System.DateTime> NgayHen { get; set; }
        public string Ca { get; set; }
        public string TrangThai { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> DaGuiEmail { get; set; }
    
        public virtual BenhNhan BenhNhan1 { get; set; }
        public virtual User User { get; set; }
    }
}
