//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dental_sys
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapVatLieu
    {
        public int id { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<int> VatLieu_id { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<int> TongTien { get; set; }
    
        public virtual VatLieu VatLieu { get; set; }
    }
}
