//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dental_sys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thu
    {
        public int id { get; set; }
        public Nullable<int> NguoiDong { get; set; }
        public Nullable<int> KhoanThu { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayThu { get; set; }
    
        public virtual Khoanthu Khoanthu1 { get; set; }
        public virtual User User { get; set; }
    }
}
