//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dental_sys
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraLuong
    {
        public int id { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<int> SoTienTra { get; set; }
        public Nullable<System.DateTime> ThangLuong { get; set; }
        public Nullable<int> NguoiDuocTra { get; set; }
    
        public virtual User User { get; set; }
    }
}
