//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dental_sys
{
    using System;
    using System.Collections.Generic;
    
    public partial class VatLieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VatLieu()
        {
            this.NhapVatLieux = new HashSet<NhapVatLieu>();
            this.XuatVatLieux = new HashSet<XuatVatLieu>();
            this.YeuCauNhaps = new HashSet<YeuCauNhap>();
            this.YeuCauXuats = new HashSet<YeuCauXuat>();
            this.NhaCungCaps = new HashSet<NhaCungCap>();
        }
    
        public int id { get; set; }
        public string TenVatLieu { get; set; }
        public string DonVi { get; set; }
        public Nullable<int> TongNhap { get; set; }
        public Nullable<int> TongXuat { get; set; }
        public Nullable<int> TonKho { get; set; }
        public Nullable<int> NhomVatLieu { get; set; }
        public Nullable<int> DonGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhapVatLieu> NhapVatLieux { get; set; }
        public virtual NhomVatLieu NhomVatLieu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XuatVatLieu> XuatVatLieux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuCauNhap> YeuCauNhaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuCauXuat> YeuCauXuats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhaCungCap> NhaCungCaps { get; set; }
    }
}
